-- 1. Table Sleep Data (Cache de sommeil)
CREATE TABLE sleep_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    date DATE NOT NULL,
    raw_data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, date)
);

-- 2. Table Daily Metrics (Cache de métriques)
CREATE TABLE daily_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    date DATE NOT NULL,
    steps INT,
    rhr INT,
    stress_avg INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, date)
);

-- 3. Table Journal (Entrées du journal)
CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL DEFAULT auth.uid(),
    date DATE NOT NULL,
    tags TEXT[], -- Array de tags: ['Caféine', 'Sport', etc.]
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(user_id, date)
);

-- 4. Activer le Row Level Security (RLS)
ALTER TABLE sleep_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

-- 5. Création des Policies (Sécurité par utilisateur)
CREATE POLICY "Users can manage own sleep_data" ON sleep_data 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage own metrics" ON daily_metrics 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can manage own journal" ON journal_entries 
FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
